sudo: required

language: php
php:
  - '7.0'

services:
  - docker

before_install:
  - docker build -t mrvil/exquisitecorpse .
  - docker run -d --name ec -p 80:80 mrvil/exquisitecorpse
  - docker ps -a

script:
  - docker exec ec service nginx status

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push mrvil/exquisitecorpse;
    fi